services:
  - type: web
    name: spjimr-rag-backend
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
    healthCheckPath: /api/health
