services:
  - type: web
    name: spjimr-rag-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
    healthCheckPath: /api/health
